import Head from "next/head";
import { getClient, sanityClient, overlayDrafts } from "../lib/sanity.server";

import BlockContent from "@sanity/block-content-to-react";

import styles from "@styles/Page.module.css";

import Image from "next/image";

import PageBlock from "@components/PageBlock";

import { pageSlug, pageContent } from "lib/queries";

export default function About({ page }) {
  const content = (page.pageBuilder || [])
    .filter((blockContent) => !blockContent.disabled)
    .map((blockContent, i) => {
      let el = null;
      switch (blockContent._type) {
        case "pageBlock":
          el = <PageBlock key={blockContent._key} content={blockContent} />;
          break;
      }
      return el;
    });

  return (
    <div className={styles.page}>
      <Head>
        <title>Mani Vintage</title>
        <meta name='description' content='Generated by create next app' />
      </Head>

      <div className={styles.content}>{content}</div>
    </div>
  );
}

export async function getStaticPaths() {
  const pages = await sanityClient.fetch(pageSlug);

  const paths = pages.map((page) => {
    return {
      params: { slug: page.slug },
    };
  });

  return {
    paths,
    fallback: false,
  };
}

export async function getStaticProps(context) {
  const slug = context.params.slug;

  const page = await sanityClient.fetch(pageContent, {
    slug: slug,
  });

  return {
    props: { page },
  };
}
