import Head from "next/head";

export default function About() {
  return (
    <>
      <Head>
        <title>Mani Vintage</title>
        <meta name='description' content='Generated by create next app' />
      </Head>
    </>
  );
}
