import Head from "next/head";
import Layout from "@components/Layout";
import PageWrapper from "@components/PageWrapper";
import React, { useState, useEffect, useRef } from "react";
import styles from "@styles/Home.module.css";
import { sanityClient } from "@lib/sanity.server";
import { getAllCategories, getNavigation } from "@lib/queries";

export default function Home() {
  React.useEffect(() => {
    // Check to see if this is a redirect back from Checkout
    const query = new URLSearchParams(window.location.search);
    if (query.get("success")) {
      console.log("Order placed! You will receive an email confirmation.");
    }

    if (query.get("canceled")) {
      console.log(
        "Order canceled -- continue to shop around and checkout when you’re ready."
      );
    }
  }, []);

  return (
    <PageWrapper>
      <Head>
        <title>Mani Vintage Test</title>
        <meta name='description' content='Generated by create next app' />
      </Head>
      <h1>Landing page</h1>
    </PageWrapper>
  );
}

export async function getStaticProps() {
  const categories = await sanityClient.fetch(getAllCategories);
  const navigation = await sanityClient.fetch(getNavigation);

  return {
    props: {
      categories,
      navigation,
    },
  };
}
